export VISUAL=vim
export EDITOR=$VISUAL
export LANG=en_US.UTF-8

# modify the prompt to contain git branch name if applicable
git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null)
  if [[ -n $ref ]]; then
    echo " %{$fg_bold[green]%}${ref#refs/heads/}%{$reset_color%}"
  fi
}
setopt promptsubst
export PS1='%{$fg_bold[green]%}%n@%M:%{$fg_bold[blue]%}%c%{$reset_color%}$(git_prompt_info)%# '

# completion
autoload -U compinit
compinit

# allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
setopt NOBGNICE

## history
setopt APPEND_HISTORY
## for sharing history between zsh processes
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

HISTSIZE=9999
SAVEHIST=9999
HISTFILE=~/.zsh_history
 
autoload -U colors
colors

setopt autocd

# vi mode
#bindkey -v
#bindkey "^F" vi-cmd-mode
#bindkey jj vi-cmd-mode

# handy keybindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward

# see http://linuxtoy.org/archives/zsh-tip-2.html
user-ret(){
   if [[ $BUFFER = "" ]] ;then
        BUFFER="ls"
        zle end-of-line
        zle accept-line
    elif [[ $BUFFER =~ "^cd\ \.\.\.+$" ]] ;then
        BUFFER=${${BUFFER//\./\.\.\/}/\.\.\//}
        zle end-of-line
        zle accept-line
    else
        zle accept-line
    fi
}

zle -N user-ret
bindkey "\r" user-ret
# end see

# ctrl+q to enqueue a command
bindkey '\eq' push-line-or-edit

# standard aliases
alias ll='ls -l'
alias la='ls -a'
alias lh='ls -lh'
alias lla='ls -la'
alias ltr='ll -tr'
alias lsr='ll -Sr'
alias fp='ps -aux | grep'
alias mv='mv -i'
alias rm='rm -i'
alias grep='grep --color=auto'
# Ubuntu xclip http://blog.csdn.net/pfanaya/article/details/7665853
alias clip=' xclip -selection clipboard '
# share current directory as a website
alias hostdir="python -m SimpleHTTPServer"

alias apt='sudo apt-get install'

# custom aliases
[[ -f ~/.aliases.local ]] && source ~/.aliases.local

# local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
